#ifndef HLTSV_H
#define HLTSV_H

#include <is/info.h>

#include <string>
#include <ostream>


// <<BeginUserCode>>

// <<EndUserCode>>

namespace hltsv
{
/**
 * 
 * @author  generated by the IS tool
 * @version 24/04/13
 */

class HLTSV : public ISInfo {
public:

    /**
     * Number of LVL1 events
     */
    uint64_t                      LVL1Events;

    /**
     * Number of assigned events
     */
    uint64_t                      AssignedEvents;

    /**
     * Number of reassigned events.
     */
    uint64_t                      ReassignedEvents;

    /**
     * Number of processed events
     */
    uint64_t                      ProcessedEvents;

    /**
     * The number of currently available cores on the DCMs.
     */
    unsigned int                  AvailableCores;

    /**
     * Average Throughput (Hz)
     */
    float                         Rate;


    static const ISType & type() {
	static const ISType type_ = HLTSV( ).ISInfo::type();
	return type_;
    }

    virtual std::ostream & print( std::ostream & out ) const {
	ISInfo::print( out );
	out << std::endl;
	out << "LVL1Events: " << LVL1Events << "\t// Number of LVL1 events" << std::endl;
	out << "AssignedEvents: " << AssignedEvents << "\t// Number of assigned events" << std::endl;
	out << "ReassignedEvents: " << ReassignedEvents << "\t// Number of reassigned events." << std::endl;
	out << "ProcessedEvents: " << ProcessedEvents << "\t// Number of processed events" << std::endl;
	out << "AvailableCores: " << AvailableCores << "\t// The number of currently available cores on the DCMs." << std::endl;
	out << "Rate: " << Rate << "\t// Average Throughput (Hz)";
	return out;
    }

    HLTSV( )
      : ISInfo( "HLTSV" )
    {
	initialize();
    }

    ~HLTSV(){

// <<BeginUserCode>>

// <<EndUserCode>>
    }

protected:
    HLTSV( const std::string & type )
      : ISInfo( type )
    {
	initialize();
    }

    void publishGuts( ISostream & out ){
	out << LVL1Events << AssignedEvents << ReassignedEvents << ProcessedEvents << AvailableCores;
	out << Rate;
    }

    void refreshGuts( ISistream & in ){
	in >> LVL1Events >> AssignedEvents >> ReassignedEvents >> ProcessedEvents >> AvailableCores;
	in >> Rate;
    }

private:
    void initialize()
    {
	LVL1Events = 0;
	AssignedEvents = 0;
	ReassignedEvents = 0;
	ProcessedEvents = 0;
	AvailableCores = 0;
	Rate = 0.0;

// <<BeginUserCode>>

// <<EndUserCode>>
    }


// <<BeginUserCode>>
public:
    void reset()
    {
        initialize();
    }

// <<EndUserCode>>
};

// <<BeginUserCode>>

// <<EndUserCode>>
inline std::ostream & operator<<( std::ostream & out, const HLTSV & info ) {
    info.print( out );
    return out;
}

}

#endif // HLTSV_H
